[workspace]
members = [
    "web-transport",
    "web-transport-proto",
    "web-transport-quinn",
    "web-transport-tauri",
    "web-transport-trait",
    "web-transport-wasm",
    "web-transport-ws",
]
resolver = "2"
