[workspace]
members = [
    "web-transport",
    "web-transport-polyfill",
    "web-transport-generic",
    "web-transport-proto",
    "web-transport-quinn",
    "web-transport-wasm",
]
resolver = "2"
