name: Rust

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      # Install Just to run CI scripts
      - uses: extractions/setup-just@v3

      # Cargo binstall is used to install tools faster than compiling them from source.
      - uses: cargo-bins/cargo-binstall@main
      - run: just setup-tools

      # Make sure u guys don't write bad code
      - run: just check
      - run: just test
