name: release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Rust with clippy/rustfmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: clippy, rustfmt

      # Set RUSTFLAGS
      - run: echo "RUSTFLAGS=--cfg=web_sys_unstable_apis" >> $GITHUB_ENV

      # Make sure u guys don't write bad code
      - run: cargo test --verbose
      - run: cargo clippy --no-deps -- -D warnings
      - run: cargo fmt --check

      # Same but for WASM
      - run: cargo check -p web-transport -p web-transport-wasm --verbose --target wasm32-unknown-unknown
      - run: cargo clippy -p web-transport -p web-transport-wasm --no-deps --target wasm32-unknown-unknown

      # Check for unused dependencies
      - uses: bnjbvr/cargo-machete@main